#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''Author: Ting'''
import logging
import traceback
from pprint import pprint
from subprocess import call
import re
from collections import defaultdict
from os.path import join, abspath, dirname, isfile
import csv
import xlrd
import matplotlib.pyplot as plt
import psycopg2

from twitter import Twitter, OAuth, TwitterHTTPError, TwitterStream
# from tweet_config import CONFIG
# from time import sleep

CONFIG = {'OAUTH_TOKEN' = '',
		  'OAUTH_SECRET' = '',
		  'CONSUMER_KEY' = '',
		  'CONSUMER_SECRET' = '',
		  'TWITTER_HANDLE' = ''}


def main():
	try:
		OAUTH_TOKEN = CONFIG.get('OAUTH_TOKEN')
		OAUTH_SECRET = CONFIG.get('OAUTH_SECRET')
		CONSUMER_KEY = CONFIG.get('CONSUMER_KEY')
		CONSUMER_SECRET = CONFIG.get('CONSUMER_SECRET')
		TWITTER_HANDLE = CONFIG.get('TWITTER_HANDLE')

		t = Twitter(auth=OAuth(OAUTH_TOKEN, OAUTH_SECRET, CONSUMER_KEY, CONSUMER_SECRET))

		while True:
			tweets = get_tweet()
			for statement in tweets:
				text = str(statement['text'].encode("utf-8"))
				print(text)
				updated_text = process_text(text) 
				send_tweet(updated_text)
			#To prevent abuse of the twitter API and usage limit, calling it only once an hour.
	 		# sleep(3600)

	except Exception as e:
		print(e)


def get_tweet():
	#Fetch the latest tweet about Donald Trump
	statement =t.search.tweets(q=”@realDonaldTrump”, count=1)
	twitter_userstream = TwitterStream(auth=auth, domain='userstream.twitter.com')
	for msg in twitter_userstream.user():
		if 'direct_message' in msg:
			print msg['direct_message']['text']
	#tweets are fetched in JSON format with a lot of related data
	tweets = statement[‘statuses’]

	return tweets


def send_tweet(text):
	#This is the part which actually posts the tweet
	if len(text)<=140:
		#Twitter allows only 140 character tweets
		print(“tweetable”)
		t.statuses.update(status=text)
	else:
		print(“140 characters crossed”)


def process_text(text): 
	handle = str(statement['user']['screen_name'])
	updated_text = '@' + handle + ' ' + textN
	print(updated_text)

	return updated_text 


if __name__ == “__main__”:
 main()


# Reference: 
# https://github.com/sixohsix/twitter/